name: BWL_REST
version: 0.0.1
description: A sample command-line application.
#author: flo <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  foo_bar: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  route: '>=0.4.0 <0.5.0'
  uuid: any
  validator: ">=0.0.4 <0.1.0"
  crypto: any
